services:
  postgres:
    ports:
      - "5433:5432" # Expose PostgreSQL local on port 5433 to docker host 5432
    environment:
      POSTGRES_DB: ${DB_NAME} # Will be hicfo_dev
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    ports:
      - "6379:6379" # Expose for development tools

  backend:
    build:
      target: development
    ports:
      - "8080:8080" # API port
      - "2345:2345" # Delve debugger port
    volumes:
      - ./api:/app
      - ./api/trusted_proxies.json:/app/trusted_proxies.json:ro # Mount trusted proxies config
    environment:
      - ENV=development
      - HOT_RELOAD=true
      - ENABLE_SWAGGER=true

      - API_PORT=${API_PORT}
      - APP_NAME=${APP_NAME}
      - TRUSTED_PROXIES_CONFIG=/app/trusted_proxies.json # Path to trusted proxies config

      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
      - frontend-network
    restart: unless-stopped
    # tmpfs:
    #   - /tmp # Use tmpfs for temporary files
    #   - /app/tmp # Use tmpfs for app temporary files

    security_opt:
      - seccomp:unconfined # For debugging

  frontend:
    build:
      target: development
    ports:
      - "3000:3000" # Next.js dev
    volumes:
      - ./web:/app # Mount source code into container
      # - /app/node_modules # Prevent overwriting node_modules
      # - /app/.next # Prevent overwriting .next build artifacts
      - nextjs-cache:/app/.next/cache
    environment:
      - NODE_ENV=development # DEV mode
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true # DEV mode
      - WATCHPACK_POLLING=true # DEV mode
      - TAILWIND_DISABLE_TOUCH=false # DEV mode
      - NEXT_PUBLIC_DEBUG=true # Enable debug mode
    networks:
      - frontend-network
    restart: unless-stopped

  nginx:
    ports:
      - "8088:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # to prevent default configs from loading
      # - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped

  # Development tools
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "30" # WARNING level (10=DEBUG, 20=INFO, 30=WARNING, 40=ERROR)
      PGADMIN_CONFIG_FILE_LOG_LEVEL: "30" # WARNING level for file logs
      GUNICORN_ACCESS_LOGFILE: "/dev/null" # Disable access logs
      PYTHONWARNINGS: "ignore" # Ignore Python warnings
    depends_on:
      - postgres
    networks:
      - backend-network

volumes:
  pgadmin_data:
  nextjs-cache:

networks:
  backend-network:
    driver: bridge
    internal: false
  frontend-network:
    driver: bridge # Frontend network allows external access via nginx
